export const STRINGS = Object.freeze({
  subtitle: 'Wカップ{大図鑑|だいずかん}',
  logoReading: 'ワールドカップペディア',
  tournaments: '{大会|たいかい}',
  records: '{記録|きろく}',
  japanFeature: '{日本代表特集|にほんだいひょうとくしゅう}',
  search: '{検索|けんさく}',
  searchLabel: '{国|くに}・{選手|せんしゅ}・{大会|たいかい}を{探|さが}す',
  loading: '{読|よ}み{込|こ}み{中|ちゅう}…',
  noSearchResults: '{見|み}つかりませんでした',
  credits: 'クレジット',
  intro: '{世界|せかい}のサッカーの{歴史|れきし}を、{大会|たいかい}から{見|み}てみよう！',
  champion: '{優勝|ゆうしょう}',
  runnerUp: '{準優勝|じゅんゆうしょう}',
  third: '3{位|い}',
  fourth: '4{位|い}',
  host: '{開催国|かいさいこく}',
  topScorer: '{得点王|とくてんおう}',
  teams: '{出場国|しゅつじょうこく}',
  matches: '{試合|しあい}',
  goals: '{得点|とくてん}',
  rank: '{順位|じゅんい}',
  country: '{国|くに}',
  played: '{試合|しあい}',
  wins: '{勝|か}ち',
  draws: '{引|ひ}き{分|わ}け',
  losses: '{負|ま}け',
  goalsFor: '{得点|とくてん}',
  goalsAgainst: '{失点|しってん}',
  goalDifference: '{得失点差|とくしってんさ}',
  points: '{勝|か}ち{点|てん}',
  advanced: '{次|つぎ}へ',
  extraTime: '{延長|えんちょう}',
  firstHalf: '{前半|ぜんはん}',
  ownGoal: 'オウンゴール',
  date: '{日付|ひづけ}',
  venue: '{会場|かいじょう}',
  goalTimeline: 'ゴールの{流|なが}れ',
  backTournament: '{大会|たいかい}に{戻|もど}る',
  home: 'ホーム',
  pageNotFound: 'ページが{見|み}つかりません',
  goHome: '{大会|たいかい}{一覧|いちらん}へ',
  dataError: 'データを{読|よ}み{込|こ}めませんでした',
  retry: 'もう{一度|いちど}{読|よ}み{込|こ}む',
  podium: '{大会|たいかい}{結果|けっか}',
  awards: '{大会|たいかい}{賞|しょう}',
  bracket: '{決勝|けっしょう}トーナメント',
  beginning: '{始|はじ}まり',
  afterRound: 'の{後|あと}',
  replay: '{再試合|さいしあい}',
  matchDetails: '{試合|しあい}の{記録|きろく}',
  dataSources: 'データの{出典|しゅってん}',
  licences: 'ライセンス',
  modified: 'データは、{必要|ひつよう}な{情報|じょうほう}を{選|えら}び、まとめ{直|なお}し、キーを{付|つ}け、{日本語名|にほんごめい}を{追加|ついか}しています。',
  flags: '{国旗|こっき}',
  siteData: 'このサイトのデータ',
  code: 'コード',
  goldenBall: 'ゴールデンボール',
  silverBall: 'シルバーボール',
  bronzeBall: 'ブロンズボール',
  goldenBoot: 'ゴールデンブーツ',
  silverBoot: 'シルバーブーツ',
  bronzeBoot: 'ブロンズブーツ',
  goldenGlove: 'ゴールデングローブ',
  bestYoungPlayer: '{最優秀若手選手|さいゆうしゅうわかてせんしゅ}',
  noGoals: 'ゴールはありません',
  todayHistory: '{今日|きょう}は{何|なん}の{日|ひ}',
  biggestWins: '{大|おお}きな{勝|か}ち',
  highestScoring: 'たくさん{点|てん}が{入|はい}った{試合|しあい}',
  hatTricks: 'ハットトリック',
  shootouts: 'PK{戦|せん}',
  japanWorldCups: '{日本|にほん}のワールドカップ',
  japanMatches: '{日本|にほん}の{試合|しあい}',
  japanScorers: '{日本|にほん}の{得点|とくてん}ランキング',
});

export const AWARD_LABELS = Object.freeze({
  'golden-ball': STRINGS.goldenBall,
  'silver-ball': STRINGS.silverBall,
  'bronze-ball': STRINGS.bronzeBall,
  'golden-boot': STRINGS.goldenBoot,
  'silver-boot': STRINGS.silverBoot,
  'bronze-boot': STRINGS.bronzeBoot,
  'golden-glove': STRINGS.goldenGlove,
  'best-young-player': STRINGS.bestYoungPlayer,
});

export const AWARD_ORDER = Object.freeze([
  'golden-ball',
  'silver-ball',
  'bronze-ball',
  'golden-boot',
  'silver-boot',
  'bronze-boot',
  'golden-glove',
  'best-young-player',
]);

export const STAGE_LABELS = Object.freeze({
  group: 'グループリーグ',
  'second-group': '{2次|にじ}リーグ',
  'final-round': '{決勝|けっしょう}リーグ',
  r32: 'ラウンド32',
  r16: 'ラウンド16',
  qf: '{準々決勝|じゅんじゅんけっしょう}',
  sf: '{準決勝|じゅんけっしょう}',
  third: '{3位決定戦|さんいけっていせん}',
  final: '{決勝|けっしょう}',
});

export const STAGE_LABELS_BY_YEAR = Object.freeze({
  1934: Object.freeze({ r16: '{1回戦|いっかいせん}' }),
  1938: Object.freeze({ r16: '{1回戦|いっかいせん}' }),
});

export function stageLabel(stage, year) {
  if (STAGE_LABELS_BY_YEAR[year]?.[stage]) return STAGE_LABELS_BY_YEAR[year][stage];
  return STAGE_LABELS[stage] || stage;
}
